config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'  # Sets the root route to PagesController#home
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/chat', to: 'chat#show', as: :chat

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_progresses
end

app/models/project_progress.rb
class ProjectProgress < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: [:user, :admin]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chat_controller.rb
# controllers/chat_controller.rb

class ChatController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @prompt = params[:prompt]
    @openai_response = OpenaiService.create_chat(@prompt) if @prompt.present?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @projects = Project.all

    # Initialize an empty hash to store progress data for each supplier
    @project_progress = {}

    # Iterate over each project to fetch its progress data for each supplier
    @projects.each do |project|
      project_progress = ProjectProgress.where(project_id: project.id)

      # If progress data exists for the project, add it to the @project_progress hash
      if project_progress.any?
        @project_progress[project.name] = project_progress
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat/show.html.erb
<!-- views/chat/show.html.erb -->

<h1 class="text-center">Chat with GPT</h1>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h2 class="text-center">Enter Prompt:</h2>
    <%= form_with url: chat_path, method: :get do |form| %>
      <div class="form-group">
        <%= form.text_area :prompt, class: 'form-control autogrow chat-text-area', rows: 3, style: 'resize: vertical;', placeholder: 'Enter your prompt here...' %>
      </div>
      <div class="row">
        <div class="col">
          <%= form.submit 'Submit', class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if @prompt.present? && @openai_response.present? %>
  <div class="row justify-content-center mt-3">
    <div class="col-md-6">
      <h2 class="text-center">Prompt:</h2>
      <pre class="code-response" style="white-space: pre-wrap;"><code><%= @prompt %></code></pre>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <div class="col-md-6">
      <h2 class="text-center">OpenAI Response:</h2>
      <pre class="code-response" style="white-space: pre-wrap;"><code><%= @openai_response['choices'][0]['message']['content'] %></code></pre>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DominoPrinting</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class=”alert alert-success”><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class=”alert alert-danger”><%= alert %></p>
    <% end %>

    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-4">
  <div class="p-4 border rounded">
    <h2 class="mb-4">Project Tracking</h2>
    <% @projects.each do |project| %>
      <h3><%= project.name %></h3>
      <div class="row">
        <% project.project_progresses.group_by(&:supplier).each do |supplier_name, progresses| %>
          <div class="col">
            <h4>Supplier: <%= supplier_name %></h4>
            <table class="table">
              <thead>
                <tr>
                  <th>Task</th>
                  <th>Date</th>
                  <th>Progress</th>
                  <th>Progress Bar</th>
                </tr>
              </thead>
              <tbody>
                <% if progresses.any? %>
                  <% progresses.each do |progress| %>
                    <tr>
                      <td><%= progress.task %></td>
                      <td><%= progress.estimated_completion %></td>
                      <td><%= progress.progress %>%</td>
                      <td>
                        <div class="progress">
                          <div class="progress-bar bg-success" role="progressbar" style="width: <%= progress.progress %>%;" aria-valuenow="<%= progress.progress %>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                <% else %>
                  <tr>
                    <td colspan="3">No progress</td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png", style: "width: 200px; height: auto;" %>
    <% end %>

    <!-- Show environment indicator -->
    <% if Rails.env.production? %>
      <div class="col-auto">
        <span class="badge bg-danger">Production</span>
      </div>
    <% elsif Rails.env.development? %>
      <div class="col-auto">
        <span class="badge bg-success">Development</span>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>